server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel
    username: dev
    password: dev
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

logging:
  level:
    org.springframework: INFO

app:
  cors:
    allowed-origins: "http://localhost:4200,http://localhost:8080"
